import React from 'react'

export default function Privacy() {
    return (
        <div className="main_documents text-justify min-vh-100 col-11 mx-auto">
        <p className="text-muted">Last updated: 8 December 2021</p>
            <ul>
                <p>This Privacy Policy describes how VendurMart and its affiliates collect, use, share or process your personal information through VendurMart's website <a href="/">www.vendurmart.com.</a></p>
                <p>While you may be able to browse certain sections of the Platform without registering with us, however, registering with us unlocks noticeable benefits. Your personal information will primarily be stored and processed in India and may have data protection laws that are different from those that apply in the country in which you are located. By visiting this Platform, providing your information, or availing our product/service, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of use, and the applicable service/product terms and conditions and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. If you do not agree please do not use or access our Platform.</p>
                <li className="text-primary">Collection of Your Information</li>
                <p>When you use our Platform, we collect and store your information which is provided by you from time to time. In general, you can browse the Platform without telling us who you are or revealing any personal information about yourself. Once you give us your personal information, you are not anonymous to us. Where possible, we indicate which fields are required and which fields are optional. You always have the option to not provide information by choosing not to use a particular service, product, or feature on the Platform.</p>
                <p>We may track your buying behavior, preferences, and other information that you choose to provide on our Platform. We use this information to do internal research on our users' demographics, interests, and behavior to better understand, protect and serve our users. This information is compiled and analyzed on an aggregated basis. This information may include the URL that you just came from (whether this URL is on our Platform or not), which URL you next go to (whether this URL is on our Platform or not), your computer browser information, and your IP address.</p>
                <p>We may collect personal information from you when you set up an account or transact with us or participate in any event or contest. While you can browse some sections of our Platform without being a registered member, certain activities do require registration. We use your contact information to send you offers based on your previous orders and your interests.</p>
                <p>If you choose to post messages on our message boards, chat rooms, or other message areas or leave feedback on the Platform or the social media handles maintained by us or if you use voice commands or virtual try and buy or similar feature to shop on the Platform, we will collect that information you provide to us. We retain this information as necessary to resolve disputes, provide customer support, troubleshoot problems, or for internal research and analysis as permitted by law.</p>
                <p>If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence about your activities or postings on the Platform, we may collect such information into a file specific to you.</p>
                <p>We will also collect your information related to your transactions on the VendurMart platform and such third-party business partner platforms. When a third-party business partner collects your personal information directly from you, you will be governed by their privacy policies. VendurMart shall not be responsible for the third-party business partner’s privacy practices or the content of their privacy policies, and we request you to read their privacy policies prior to disclosing any information.</p>
                <p>VendurMart has onboarded certain third-party business partners on the Platform who specialize in the categories like travel ticket reservations, booking online movie tickets, paying online bills, and more. If you use the services of such third parties, you will be redirected to their websites/applications and your entry to their websites/applications will be based on your VendurMart login credentials after seeking your permissions to share the data further. VendurMart shall not be responsible for the third parties’ privacy practices or the content of their privacy policies, and we request you to read their privacy policies prior to disclosing any information.</p>
                <li className="text-primary">Use of Demographic / Profile Data / Your Information</li>
                <p>We use your personal information to provide the product and services you request. To the extent we use your personal information to market to you, we will provide you the ability to opt out of such uses. We use your personal information to assist sellers and business partners in handling and fulfilling orders; enhancing the customer experience; resolving disputes; troubleshoot problems; help promote a safe service; collecting money; measuring consumer interest in our products and services; inform you about online and offline offers, products, services, and updates; customize and enhance your experience; detect and protect us against error, fraud, and other criminal activity; enforce our terms and conditions; and as otherwise described to you at the time of collection of information.</p>
                <p>With your consent, we may have access to your SMS, instant messages, contacts in your directory, location, camera, photo gallery, and device information. We may also request you to provide your PAN, GST Number, Government issued ID cards/number, and Know-Your-Customer (KYC) details to </p>
                <ol type="i">
                    <li>Check your eligibility for certain products and services including but not limited to credit and payment products</li>
                    <li>Issue GST invoice for the products and services purchased for your business requirements.</li>
                    <li>Enhance your experience on the Platform and provide you access to the products and services being offered by us, sellers, affiliates or lending partners. You understand that your access to these products/services may be affected in the event consent is not provided to us.</li>
                </ol><br/>
                <p>In our efforts to continually improve our product and service offerings, we and our affiliates collect and analyze demographic and profile data about our users' activity on our Platform. We identify and use your IP address to help diagnose problems with our server and to administer our Platform. Your IP address is also used to help identify you and to gather broad demographic information.</p>
                <p>We will occasionally ask you to participate in optional surveys conducted either by us or through a third-party market research agency. These surveys may ask you for personal information, contact information, date of birth, demographic information, attributes such as your interests, household or lifestyle information, your purchasing behavior or history, preferences, and other such information that you may choose to provide. The surveys may involve the collection of voice data or video recordings, the participation of which would purely be voluntary in nature. We use this data to tailor your experience at our Platform, providing you with content that we think you might be interested in and displaying the content according to your preferences.</p>
                <li className="text-primary">Cookies</li>
                <p>We use data collection devices such as "cookies" on certain pages of the Platform to help analyze our web page flow, measure promotional effectiveness, and promote trust and safety. "Cookies" are small files placed on your hard drive that assist us in providing our services. Cookies do not contain any of your personal information. We offer certain features that are only available through the use of a "cookie". We also use cookies to allow you to enter your password less frequently during a session. Cookies can also help us provide information that is targeted to your interests. Most cookies are "session cookies," meaning that they are automatically deleted from your hard drive at the end of a session. You are always free to decline/delete our cookies if your browser permits, although in that case, you may not be able to use certain features on the Platform and you may be required to re-enter your password more frequently during a session. Additionally, you may encounter "cookies" or other similar devices on certain pages of the Platform that are placed by third parties. We do not control the use of cookies by third parties. We use cookies from third-party partners such as Google Analytics for marketing and analytical purposes. Google Analytics helps us understand how our customers use the site.</p>
                <li className="text-primary">Sharing of personal information</li>
                <p>We may share personal information internally within VendurMart group companies, affiliates, related companies, and with other third parties for purposes of providing products and services offered by them. These entities and affiliates may share such information with their affiliates, business partners, and other third parties for the purpose of providing you their products and services and may market to you as a result of such sharing unless you explicitly opt-out.</p>
                <p>We may disclose your personal information to third parties, such as sellers, business partners. This disclosure may be required for us to provide you access to our products and services; for the fulfillment of your orders; for enhancing your experience; for providing feedback on products; to collect payments from you; to comply with our legal obligations; to conduct market research or surveys; to enforce our Terms of Use; to facilitate our marketing and advertising activities; to analyze data; for customer service assistance; to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our product and services. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.</p>
                <p>We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. We may disclose personal information to law enforcement agencies, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms of Use or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.</p>
                <p>We and our affiliates will share/sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that another business entity (or the new combined entity) will be required to follow this Privacy Policy with respect to your personal information.</p>
                <li className="text-primary">Links to Other Sites</li>
                <p>Our Platform may provide links to other websites or applications that may collect personal information about you. We are not responsible for the privacy practices or the content of those linked websites.</p>
                <li className="text-primary">Security Precautions</li>
                <p>We maintain reasonable physical, electronic and procedural safeguards to protect your information. Whenever you access your account information, we offer the use of a secure server. Once your information is in our possession, we adhere to our security guidelines to protect it against unauthorized access. However, by using the Platform, the users accept the inherent security implications of data transmission over the internet and the World Wide Web which cannot always be guaranteed as completely secure, and therefore, there would always remain certain inherent risks regarding the use of the Platform. Users are responsible for ensuring the protection of login and password records for their accounts.</p>
                <li className="text-primary">Choice/Opt-Out</li>
                <p>We provide all users with the opportunity to opt-out of receiving non-essential communications after setting up an account with us.</p>
                <li className="text-primary">Advertisements on Platform</li>
                <p>We use third-party advertising companies to serve ads when you visit our Platform. These companies may use information (not including your name, address, email address, or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.</p>
                <li className="text-primary">Children Information</li>
                <p>Use of our Platform is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. We do not knowingly solicit or collect personal information from children under the age of 18 years. If you have shared any personal information of children under the age of 18 years, you represent that you have the authority to do so and permit us to use the information in accordance with this Privacy Policy.</p>
                <li className="text-primary">Data Retention</li>
                <p>We retain your personal information in accordance with appliable laws, for a period no longer than is required for the purpose for which it was collected or as required under any applicable law. However, we may retain data related to you if we believe it may be necessary to prevent fraud or future abuse, to enable VendurMart to exercise its legal rights and/or defend against legal claims or if required by law or for other legitimate purposes. We may continue to retain your data in anonymized form for analytical and research purposes.</p>
                <li className="text-primary">Your Rights</li>
                <p>We take every reasonable step to ensure that your personal information that we process is accurate and, where necessary, kept up to date, and any of your personal information that we process that you inform us is inaccurate is erased or rectified. You may access, correct, and update your personal information directly through the functionalities provided on the Platform. You may delete certain non-mandatory information by logging into our website and visiting the Profile and Settings sections. You can also write to us at the contact information provided below to assist you with these requests.</p>
                <p>You have an option to withdraw your consent that you have already provided by writing to us at the contact information provided below. Please mention “for withdrawal of consent” in the subject line of your communication. We will verify such requests before acting upon your request. Please note, however, that withdrawal of consent will not be retroactive and will be in accordance with the terms of this Privacy Policy, related Terms of Use, and applicable laws. In the event you withdraw the consent given to us under this Privacy Policy, such withdrawal may hamper your access to the Platform or restrict the provision of our services to you for which we consider that information to be necessary.</p>
                <li className="text-primary">Your Consent</li>
                <p>By visiting our Platform or by providing your information, you consent to the collection, use, storage, disclosure, and otherwise processing of your information (including sensitive personal information) on the Platform in accordance with this Privacy Policy. If you disclose to us any personal information relating to other people, you represent that you have the authority to do so and to permit us to use the information in accordance with this Privacy Policy.</p>
                <p>You, while providing your personal information over the Platform or any partner platforms or establishments, consent to us (including our other corporate entities, affiliates, lending partners, technology partners, marketing channels, business partners, and other third parties) to contact you through SMS, instant messaging apps, call and/or e-mail for the purposes specified in this Privacy Policy.</p>
                <li className="text-primary">Changes to this Privacy Policy</li>
                <p>Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our information practices. We will alert you to significant changes by posting the date our policy got last updated, placing a notice on our Platform, or by sending you an email when we are required to do so by applicable law.</p>
                <li className="text-primary">Queries related to Privacy Policy</li>
                <p>If you have a query, concern, or complaint in relation to the collection or usage of your personal information under this Privacy Policy, please contact us at the contact information provided</p>
                <p>Email: <a className="text-decoration-none" href="mailto:vendurmart@gmail.com">vendurmart@gmail.com</a></p>
            </ul>
        </div>
    )
}
